# Generated by Django 2.0.7 on 2018-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight',
            field=models.TextField(),
        ),
    ]
