# Generated by Django 2.0.7 on 2018-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180721_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='highlight',
            field=models.TextField(null=True),
        ),
    ]
