# Generated by Django 2.0.7 on 2018-07-24 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180724_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
